eureka:
  instance:
    prefer-ip-address: true
#    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
#      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      override-system-properties: false

management:
  zipkin:
    sampling:
      probability: 1.0